services:
  db:
    image: postgres
    container_name: postgresql_container
    ports:
      - 5434:5432
    environment:
      - POSTGRES_DB=tweteroo
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    restart: always
    
  api:
    build: .
    container_name: api_container
    ports:
     - 80:8080
    environment:
      db-url: jdbc:postgresql://db:5432/tweteroo
      db_username: postgres
      db_password: root
    depends_on:
      - db

volumes:
  postgres-volume: